spring:
  rabbitmq:
    addresses: 47.112.7.219
    port: 5672
    username: guest
    password: guest

server:
  port: 8084
 
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
#      sensitiveHeaders:
#    product: /myProduct/**

  ignored-patterns:
    - /**/product/decreaseStock
    - /**/product/listForOrder
  sensitive-headers: 
