spring:
  application:
    name: order
  datasource:
    username: root
    password: ITkaven@123
    url: jdbc:mysql://47.112.7.219:3306/sell?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 47.112.7.219
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
kaven: wyuanyuan
