spring:
  rabbitmq:
    addresses: 47.112.7.219
    port: 5672
    username: guest
    password: guest
  datasource:
    username: root
    password: ITkaven@123
    url: jdbc:mysql://47.112.7.219:3306/sell?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

server:
  port: 8081


